name: WorkFlow 2
on: [issues, workflow_dispatch]
jobs:
    issues-trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Output Issues
              run: echo "${{ github.event}}"
    condition-issues-trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Output Issues
              run: echo "${{ github.event_name == 'issues' && github.event}}"