name: WorkFlow 1
on: push
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Pull code from repo
              uses: actions/checkout@v3
            - name: Setup nodejs environment
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependency
              run: npm ci
            - name: Run Lint
              run: npm run lint
            - name: Run test
              run: npm test
            - name: Run build
              run: npm run build
            