name: WorkFlow 1
on: push
jobs:
    run-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Pull code from repo
              uses: actions/checkout@v3
            - name: Setup nodejs environment
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependency
              run: npm ci
            - name: Run Lint
              run: npm run lint
    run-test:
        runs-on: ubuntu-latest
        needs: run-lint
        steps:
            - name: Pull code from repo
              uses: actions/checkout@v3
            - name: Setup nodejs environment
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependency
              run: npm ci
            - name: Run Test
              run: npm test
    run-build:
        runs-on: ubuntu-latest
        needs: run-test
        steps:
            - name: Pull code from repo
              uses: actions/checkout@v3
            - name: Setup nodejs environment
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependency
              run: npm ci
            - name: Run Build
              run: npm run build